import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import styles from './MessageRenderer.module.css';

interface MessageRendererProps {
  content: string;
  onShowCitation: (text: string) => void;
  sessionId: string;
}

export default function MessageRenderer({ content, onShowCitation, sessionId }: MessageRendererProps) {
  // Regex to match <think>...</think>, <tool_call>...</tool_call>, and <tool_result>...</tool_result>
  const blockRegex = /<(think|tool_call|tool_result)>([\s\S]*?)<\/\1>/g;
  
  const blocks = [];
  let lastIndex = 0;
  let match;

  while ((match = blockRegex.exec(content)) !== null) {
    if (match.index > lastIndex) {
      blocks.push({ type: 'markdown', content: content.slice(lastIndex, match.index) });
    }
    blocks.push({ type: match[1], content: match[2] });
    lastIndex = match.index + match[0].length;
  }
  
  if (lastIndex < content.length) {
    // Check if there is an unclosed tag at the end (for streaming)
    const remaining = content.slice(lastIndex);
    const unclosedMatch = remaining.match(/<(think|tool_call|tool_result)>/);
    if (unclosedMatch) {
      const parts = remaining.split(`\x3C${unclosedMatch[1]}\x3E`); // Use hex to avoid parse issue
      if (parts[0]) blocks.push({ type: 'markdown', content: parts[0] });
      blocks.push({ type: unclosedMatch[1], content: parts[1] || '', isStreaming: true });
    } else {
      blocks.push({ type: 'markdown', content: remaining });
    }
  }

  // A custom renderer component for links or citations could be added here
  // For now we will intercept click events on the wrapper to handle citations
  const handleCitationClick = (e: React.MouseEvent) => {
    const target = e.target as HTMLElement;
    if (target.tagName === 'SUP' || target.classList.contains('citation')) {
      const toolResultRegex = /<tool_result>([\s\S]*?)<\/tool_result>/g;
      let toolResultsContext = '';
      let trMatch;
      while ((trMatch = toolResultRegex.exec(content)) !== null) {
        let rawText = trMatch[1].replace(/```(json)?/g, '').trim();
        try {
          const parsed = JSON.parse(rawText);
          if (parsed.output) {
            toolResultsContext += parsed.output + '\n\n---\n\n';
          } else {
            toolResultsContext += rawText + '\n\n---\n\n';
          }
        } catch (e) {
          toolResultsContext += rawText + '\n\n---\n\n';
        }
      }
      
      const text = toolResultsContext.trim() 
        ? `**溯源上下文:**\n\n${toolResultsContext}` 
        : `未找到关联的知识库原文。`;
      onShowCitation(text);
    }
  };

  // Pre-process markdown to convert [1], [2] into click-able spans
  const renderMarkdown = (text: string) => {
    // We convert it to a markdown link so ReactMarkdown parses it correctly
    const processed = text.replace(/\[(\d+)\]/g, '[$1](#citation-$1)');
    
    return (
      <div onClick={handleCitationClick}>
        <ReactMarkdown 
          remarkPlugins={[remarkGfm]}
          components={{
            a: ({node, ...props}) => {
              // Handle citation links
              if (props.href?.startsWith('#citation-')) {
                const id = props.href.replace('#citation-', '');
                return <sup className="citation" data-id={id}>[{id}]</sup>;
              }
              // Handle file links generated by the agent (e.g. ./workspace/file.csv)
              if (props.href?.startsWith('./workspace/')) {
                const filename = props.href.split('/').pop();
                return (
                  <a 
                    href={`http://localhost:3000/api/sessions/${sessionId}/download/${filename}`} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className={styles.fileDownloadLink}
                  >
                    <i className="ri-file-download-line"></i> 下载 {filename}
                  </a>
                );
              }
              return <a {...props} />;
            }
          }}
        >
          {processed}
        </ReactMarkdown>
      </div>
    );
  };

  return (
    <div className={styles.renderer}>
      {blocks.map((block, i) => {
        if (block.type === 'think' || block.type === 'tool_call' || block.type === 'tool_result') {
          let icon = "ri-brain-line";
          let title = "思考过程";
          if (block.type === 'tool_call') {
            icon = "ri-tools-line";
            title = "工具调用";
          } else if (block.type === 'tool_result') {
            icon = "ri-code-box-line";
            title = "执行结果";
          }
          
          if (block.isStreaming) {
            title = "正在" + title.replace("过程", "");
          }
          
          return (
            <details key={i} className={styles.thinkBlock} open={block.isStreaming}>
              <summary>
                <i className={icon}></i> 
                {title}
              </summary>
              <div className={styles.thinkContent}>
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{block.content}</ReactMarkdown>
              </div>
            </details>
          );
        }
        
        // Handle tool output block (which is wrapped in **Tool Result:**)
        if (block.type === 'markdown') {
          return <div key={i} className={styles.markdownBlock}>{renderMarkdown(block.content)}</div>;
        }
        
        return null;
      })}
    </div>
  );
}
